version: '2'
services:
  ui:
    build:
      context: ./app/ui
    container_name: ui
    ports:
      - "3000:3000"
      - "35729:35729"
    volumes:
      - ./app/ui:/ui

    networks:
      - bioalign

  api:
    build:
      context: ./app/api
    container_name: api
    ports:
      - "4000:4000"
    volumes:
      - ./app/api:/api

    networks:
      - bioalign

networks:
  bioalign:
    driver: bridge     