version: '2'
services:
  ui:
    build:
      context: ./app/ui
    container_name: ui
    ports:
      - "3000:3000"
      - "35729:35729"
    volumes:
      - ./app/ui:/ui

    networks:
      - bioalign

  api:
    build:
      context: ./app/api
    container_name: api
    ports:
      - "4000:80"
    volumes:
      - ./app/api:/api
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

    networks:
      - bioalign

  compute:
    build:
      context: ./app/compute
    container_name: compute
    ports:
      - "5000:5000"
    volumes:
      - ./app/compute:/compute
    environment:
      - PYTHONUNBUFFERED=1
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY

    networks:
      - bioalign

  bdd:
    build:
      context: ./tests/bdd
    container_name: bdd
    volumes:
      - ./tests/bdd:/bdd
    environment:
      - API_URL=http://api
    depends_on:
      - ui
      - api
      - compute

    networks:
      - bioalign


networks:
  bioalign:
    driver: bridge     