swagger: "2.0"
info:
  version: "0.0.1"
  title: bioalign API
# basePath prefixes all resource paths 
basePath: /api/v1
# 
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /alignments:
    x-swagger-router-controller: alignments
    post:
      tags : [ Alignment ]
      description: Request a new asynchronous alignment
      operationId: requestAlignment
      parameters:
        - name: request
          in: body
          description: Alignment specification
          required: true
          schema:
            $ref: "#/definitions/AlignRequest"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AlignTask"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /alignments/{id}:
    x-swagger-router-controller: alignments
    get:
      tags : [ Alignment ]
      description: Get durable result of completed alignment
      operationId: getAlignment
      parameters:
        - name: id
          in: path
          description: Alignment id
          required: true
          type: number
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AlignResponse"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /tasks/{taskId}:
    x-swagger-router-controller: tasks
    get:
      tags : [ Alignment ]
      description: Get status of an ongoing or recent alignment
      operationId: requestStatus
      parameters:
        - name: taskId
          in: path
          description: Task identifier
          required: true
          type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AlignStatus"
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
  /health:
    x-swagger-router-controller: health
    get:
      tags : [ Health ]
      description: Check health
      operationId: checkHealth
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HealthResponse"
definitions:
  AlignRequest:
    required:
      - sequence
    properties:
      sequence:
        type: string
        example: AATCCGCTAG
  AlignTask:
    required:
      - taskId
      - href
    properties:
      taskId:
        type: string
      href:
        type: string
  AlignStatus:
    properties:
      taskId:
        type: string
      status:
        type: string
      message:
        type: string
  AlignResponse:
    properties:
      sequence:
        type: string
      found:
        type: boolean
      proteinName:
        type: string
      proteinPosition:
        type: number
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  HealthResponse:
    description: Health result
    type: string
