swagger: "2.0"
info:
  version: "0.0.1"
  title: bioalign API
# basePath prefixes all resource paths 
basePath: /api/v1
# 
consumes:
  - application/json
# format of the responses to the client (Accepts)
produces:
  - application/json
paths:
  /health:
    x-swagger-router-controller: health
    get:
      description: Check health
      operationId: checkHealth
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/HealthResponse"
  /alignments:
    x-swagger-router-controller: alignments
    post:
      description: Request a new asynchronous alignment
      operationId: alignRequest
      parameters:
        - name: request
          in: body
          description: Alignment specification
          required: true
          schema:
            $ref: "#/definitions/AlignRequest"
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/AlignTask"
        # responses may fall through to errors
        default:
          description: Error
          schema:
            $ref: "#/definitions/ErrorResponse"
# complex objects have schema definitions
definitions:
  AlignRequest:
    required:
      - sequence
    properties:
      sequence:
        type: string
  AlignTask:
    required:
      - taskId
      - href
    properties:
      taskId:
        type: string
      href:
        type: string
  ErrorResponse:
    required:
      - message
    properties:
      message:
        type: string
  HealthResponse:
    description: Health result
    type: string
